name: Deploy Kalenderin

on:
    push:
        branches:
            - main
            - development
    workflow_dispatch:

permissions:
    contents: read
    pages: write
    id-token: write

concurrency:
    group: pages
    cancel-in-progress: true

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout current branch
              uses: actions/checkout@v4

            - name: Set up Node
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: npm

            - name: Install dependencies
              run: npm ci

            - name: Build app
              run: npm run build

            - name: Move development build to /dev
              if: github.ref_name == 'development'
              run: |
                  mkdir deploy
                  mv dist deploy/dev

            - name: Move main build to root
              if: github.ref_name == 'main'
              run: |
                  mkdir deploy
                  mv dist/* deploy/

            - name: Setup Pages
              uses: actions/configure-pages@v5

            - name: Upload artifact
              uses: actions/upload-pages-artifact@v3
              with:
                  path: deploy

            - name: Deploy to GitHub Pages
              uses: actions/deploy-pages@v4
